import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { Poppins } from "next/font/google";

import Head from "next/head";
import Script from "next/script";

const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  style: "normal",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Nandha Food Restaraunt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <>
          <Script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            strategy="beforeInteractive"
          />

          <Script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            strategy="beforeInteractive"
          />
          <Script
            src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"
            strategy="beforeInteractive"
          />
        </>
      </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
